# This file is generated by elixir_config bzlmod extension

load(
    "@rules_elixir//:elixir_toolchain.bzl",
    "elixir_toolchain",
)

# Reference the built Elixir from the source repository
alias(
    name = "elixir_build",
    actual = "@elixir_source_%{ELIXIR_NAME}//:elixir_build",
    visibility = ["//visibility:public"],
)

elixir_toolchain(
    name = "elixir",
    elixir = ":elixir_build",
    visibility = ["//visibility:public"],
)

toolchain(
    name = "toolchain",
    exec_compatible_with = [
        "//:elixir_internal",
    ],
    target_compatible_with = [
        "//:elixir_%{ELIXIR_VERSION_ID}",
    ],
    toolchain = ":elixir",
    toolchain_type = "@rules_elixir//:toolchain_type",
    visibility = ["//visibility:public"],
)
